export const CFG = {
	areas: {
		"CG": "Castle Grounds",
		"DC-SPT": "Spirit Temple",
		"DC": "Desert Colossus",
		"DMC-FIT": "Death Mtn Crater - Fire Temple",
		"DMC": "Death Mountain Crater",
		"DMT-DC": "Dodongo's Cavern",
		"DMT": "Death Mountain Trail",
		"G-DH": "Dampe's Hut",
		"GU-SHT": "Shadow Temple",
		"GL": "Graveyard - Lower",
		"GU": "Graveyard - Upper",
		"GC-SH": "Goron City Shop",
		"GC": "Goron City",
		"GF-GTG": "Gerudo Training Grounds",
		"GF": "Gerudo Fortress",
		"GV-CT": "Gerudo Valley - Carpenter's Tent",
		"GV": "Gerudo Valley",
		"HF": "Hyrule Field",
		"HW": "Haunted Wasteland",
		"KF-DT": "Deku Tree",
		"KF-HOT": "House of Twins",
		"KF-KIAH": "House of the Know It All Brothers",
		"KF-LH": "Link's House",
		"KF-MH": "Mido's House",
		"KF-SAH": "Saria's House",
		"KF-SH": "Kokiri Forest Shop",
		"KF": "Kokiri Forest",
		"KV-BOTW": "Bottom of the Well",
		"KV-CC": "Hole in Impa's House",
		"KV-CH": "Carpenter's House",
		"KV-HOS": "House of Skulltula",
		"KV-IM": "Impa's House",
		"KV-SG": "Kakariko Village Shooting Gallery",
		"KV-SH-B": "Kakariko Village Bazaar",
		"KV-SH-P": "Kakariko Village Potion Shop",
		"KV-W": "Windmill",
		"KV": "Kakariko Village",
		"KVB": "Kakariko Village Backyard",
		"KVB-ODM": "Kakariko Village Odd Medicine Bldg",
		"LH-FH": "Fishing Hole",
		"LH-LL": "Lakeside Lab",
		"LH-WT": "Water Temple",
		"LH": "Lake Hylia",
		"LLR-S": "Lon Lon Ranch Stables",
		"LLR-T": "Lon Lon Ranch Tower",
		"LLR-TH": "Talon's House",
		"LLR": "Lon Lon Ranch",
		"LW": "Lost Woods",
		"LWB": "Lost Woods Bridge",
		"M-BB": "Bombchu Bowling",
		"M-MGH": "Market - Man in Green Residence",
		"M-SG": "Market Shooting Gallery",
		"M-SH-B": "Market Bazaar",
		"M-SH-BC": "Market Bombchu Shop",
		"M-SH-M": "Market Mask Shop",
		"M-SH-P": "Market Potion Shop",
		"M-TCG": "Market Treasure Chest Game",
		"M": "Market",
		"ME-GH": "Guard House",
		"ME": "Market Entr.",
		"SFM-FOT": "Forest Temple",
		"SFM": "Sacred Forest Meadow",
		"TOTC-TOT": "Temple of Time",
		"TOTC": "Temple of Time Courtyard",
		"ZD-SH": "Zora's Domain Shop",
		"ZD": "Zora's Domain",
		"ZF-IC": "Ice Cavern",
		"ZF-JJB": "Jaba Jaba's Belly",
		"ZF": "Zora's Fountain",
		"ZR": "Zora's River",


		"CG-G": "Grotto, Breakable Walls",
		"DC-G": "Grotto, Two Scrubs",
		"DMC-G-H": "Grotto, Three Scrubs",
		"DMC-G-U": "Grotto, Chest",
		"DMT-G-C": "Grotto, Cow",
		"DMT-G-S": "Grotto, Chest",
		"G-G-D": "Grotto, Dampe's Grave",
		"G-G-HP": "Grotto, Single ReDead",
		"G-G-RF": "Grotto, Royal Family Tomb",
		"G-G-S": "Grotto, Chest and Fairy Fountain",
		"GC-G": "Grotto, Three Scrubs",
		"GF-G": "Grotto, Fairy Fountain",
		"GV-G-FS": "Grotto, Two Scrubs",
		"GV-G-O": "Grotto, Octorok",
		"HF-G-C": "Grotto, Spider Webs",
		"HF-G-F": "Grotto, Fairy Fountain",
		"HF-G-IF": "Grotto, Single Scrub",
		"HF-G-NK": "Grotto, Gold Skulltula",
		"HF-G-NM": "Grotto, Chest",
		"HF-G-O": "Grotto, Chest",
		"HF-G-SE": "Grotto, Chest",
		"HF-G-T": "Grotto, Pool",
		"KV-G": "Grotto, Two ReDeads",
		"KF-G": "Grotto, Chest",
		"KVB-G": "Grotto, Chest",
		"LH-G": "Grotto, Three Scrubs",
		"LLR-G": "Grotto, Three Scrubs",
		"LW-G-DT": "Grotto, Deku Theater",
		"LW-G-NS": "Grotto, Chest",
		"LW-G-S": "Grotto, Two Scrubs",
		"SFM-G-F": "Grotto, Fairy Fountain",
		"SFM-G-S": "Grotto, Two Scrubs",
		"SFM-G-W": "Grotto, Wolfos",
		"ZD-G": "Grotto, Fairy Fountain",
		"ZR-G-F": "Grotto, Fairy Fountain",
		"ZR-G-O": "Grotto, Chest",
		"ZR-G-S": "Grotto, Two Scrubs",
		"CG-GFF-C": "Great F.F. (Din's Fire)",
		"DC-GFF": "Great F.F. (Nayru's Love)",
		"DMC-GFF": "Great F.F. (Double Magic)",
		"DMT-GFF": "Great F.F. (Magic Meter)",
		"CG-GFF-A": "Great F.F. (Double Defense)",
		"ZF-GFF": "Great F.F. (Farore's Wind)",

		"OWL-LH": "Owl Lake Hylia",
		"OWL-DMT": "Death Mountain Trail Owl",
	} as Record<string, string>,

	doors: {
		"M-BB/M": "Market - Bombchu Bowling Exit",
		"KV-CC/KV": "Kakariko V. - Impa's House Hole Exit",
		"KV-CH/KV": "Kakariko V. - Carpenter's House Exit",
		"GV-CT/GV": "Gerudo Valley - Carpenter's Tent Exit",
		"GL-DH/GL": "Graveyard - Dampe's Hut Exit",
		"LH-FH/LH": "Lake Hylia - Fishing Hole Exit",
		"CG-G/CG": "Grotto, Breakable Walls",
		"DC-G/DC": "Grotto, Two Scrubs",
		"DMC-G-H/DMC": "Grotto, Three Scrubs",
		"DMC-G-U/DMC": "Grotto, Chest",
		"DMT-G-C/DM": "Grotto, Cow",
		"DMT-G-S/DM": "Grotto, Chest",
		"G-G-D/G": "Grotto, Dampe's Grave",
		"G-G-HP/G": "Grotto, Single ReDead",
		"G-G-RF/G": "Grotto, Royal Family Tomb",
		"G-G-S/G": "Grotto, Chest and Fairy Fountain",
		"GC-G/GC": "Grotto, Three Scrubs",
		"GF-G/GF": "Grotto, Fairy Fountain",
		"GV-G-FS/GV": "Grotto, Two Scrubs",
		"GV-G-O/GV": "Grotto, Octorok",
		"HF-G-C/HF": "Grotto, Spider Webs",
		"HF-G-F/HF": "Grotto, Fairy Fountain",
		"HF-G-IF/HF": "Grotto, Single Scrub",
		"HF-G-NK/HF": "Grotto, Gold Skulltula",
		"HF-G-NM/HF": "Grotto, Chest",
		"HF-G-O/HF": "Grotto, Chest",
		"HF-G-SE/HF": "Grotto, Chest",
		"HF-G-T/HF": "Grotto, Pool",
		"KV-G/KV": "Grotto, Two ReDeads",
		"KF-G/KF": "Grotto, Chest",
		"KVB-G/KVB": "Grotto, Chest",
		"LH-G/LH": "Grotto, Three Scrubs",
		"LLR-G/LLR": "Grotto, Three Scrubs",
		"LW-G-DT/LW": "Grotto, Deku Theater",
		"LW-G-NS/LW": "Grotto, Chest",
		"LW-G-S/LW": "Grotto, Two Scrubs",
		"SFM-G-F/SFM": "Grotto, Fairy Fountain",
		"SFM-G-S/SFM": "Grotto, Two Scrubs",
		"SFM-G-W/SFM": "Grotto, Wolfos",
		"ZD-G/ZD": "Grotto, Fairy Fountain",
		"ZR-G-F/ZR": "Grotto, Fairy Fountain",
		"ZR-G-O/ZR": "Grotto, Chest",
		"ZR-G-S/ZR": "Grotto, Two Scrubs",

		"CG/CG-G": "Castle Grounds Grotto Entr.",
		"DC/DC-G": "Desert Colossus Grotto Entr.",
		"DMC/DMC-G-H": "Death M.C. Grotto Entr., Boulder",
		"DMC/DMC-G-U": "Death M.C. Grotto Entr., Upper",
		"DM/DMT-G-C": "Death Mountain Trail Grotto Entr., Cow",
		"DM/DMT-G-S": "Death M.T. Grotto Entr., Ring of Rocks",
		"GL/GL-G-D": "Graveyard Grave, Dampe's Grave",
		"GL/GL-G-HP": "Graveyard Grave, back, 4th from right",
		"GL/GL-G-RF": "Graveyard Grave, Royal Family Tomb",
		"GL/GL-G-S": "Graveyard Grave, front, 2nd from left",
		"GC/GC-G": "Goron City Grotto Entr.",
		"GF/GF-G": "Gerudo Fortress Grotto Entr.",
		"GV/GV-G-FS": "Gerudo Valley Grotto Entr., Behind Tent",
		"GV/GV-G-O": "Gerudo Valley Grotto Entr., Boulder",
		"HF/HF-G-C": "Hyrule Field Grotto Entr., Near G.V.",
		"HF/HF-G-F": "Hyrule Field Grotto Entr., NW Corner",
		"HF/HF-G-IF": "Hyrule Field Grotto Entr., Inside Fence",
		"HF/HF-G-NK": "Hyrule Field Grotto Entr., Near Kakariko",
		"HF/HF-G-NM": "Hyrule Field Grotto Entr., Outside Market",
		"HF/HF-G-O": "Hyrule Field Grotto Entr., Open",
		"HF/HF-G-SE": "Hyrule Field Grotto Entr., Southeast",
		"HF/HF-G-T": "Hyrule Field Grotto Entr., NW of Ranch",
		"KV/KV-G": "Kakariko V. Grotto Entr.",
		"KF/KF-G": "Kokiri Forest Grotto Entr., Frontyard",
		"KVB/KVB-G": "Kakariko V. Grotto Entr., Backyard",
		"LH/LH-G": "Lake Hylia Grotto Entr.",
		"LLR/LLR-G": "Lon Lon Ranch Grotto Entr.",
		"LW/LW-G-DT": "Lost Woods Grotto Entr., Beside Tree",
		"LW/LW-G-NS": "Lost Woods Grotto Entr., Near Goron City",
		"LW/LW-G-S": "Lost Woods Grotto Entr., Boulder",
		"SFM/SFM-G-F": "Sacred F.M. Grotto Entr., Ladder",
		"SFM/SFM-G-S": "Sacred F.M. Grotto Entr., Forest Temple",
		"SFM/SFM-G-W": "Sacred F.M. Grotto Entr., Frontyard",
		"ZD/ZD-G": "Zora's Domain Grotto Entr.",
		"ZR/ZR-G-F": "Zora's River Grotto Entr., Boulder",
		"ZR/ZR-G-O": "Zora's River Grotto Entr., Open",
		"ZR/ZR-G-S": "Zora's River Grotto Entr., Ring of Rocks",

		"CG-GFF-C/CG": "Great F.F. Exit (Din's Fire)",
		"DC-GFF/DC": "Great F.F. Exit (Naryru's Love)",
		"DMC-GFF/DMC": "Great F.F. Exit (Double Magic)",
		"DMT-GFF/DMT": "Great F.F. Exit (Magic Meter)",
		"CG-GFF-A/CG": "Great F.F. Exit (Double Defense)",
		"ZF-GFF/ZF": "Great F.F. Exit (Farore's Wind)",
		"KV-HOS/KV": "Kakariko V. - House of Skulltula Exit",
		"KF-HOT/KF": "Kokiri Forest - House of Twins Exit ",
		"KV-IM/KV": "Kakariko V. - Impa's House Exit",
		"KF-KIAH/KF": "Kokiri Forest - Know it all House Exit",
		"KF-LH/KF": "Kokiri Forest - Link's House Exit",
		"LH-LL/LH": "Lake Hylia - Lakeside Lab Exit",
		"M-MGH/M": "Market - Man in Green House Exit",
		"ME-GH/ME": "Market Entr. - Guard House Exit",
		"KF-MH/KF": "Kokiri Forest - Mido's House Exit",
		"KVB-ODM/KVB": "Kakariko V. - Odd Medicine Bldg Exit",
		"LLR-S/LLR": "Lon Lon Ranch - Ranch Stables Exit",
		"KV-SG/KV": "Kakariko V. - Shooting Gallery Exit",
		"M-SG/M": "Market - Shooting Gallery Exit",
		"KV-SH-B/KV": "Kakariko V. - Bazaar Exit",
		"M-SH-B/M": "Market - Bazaar Exit",
		"M-SH-BC/M": "Market - Bombchu Shop Exit",
		"GC-SH/GC": "Goron City - Shop Exit",
		"KF-SAH/KF": "Kokiri Forest - Saria's House Exit",
		"KF-SH/KF": "Kokiri Forest - Shop Exit",
		"M-SH-M/M": "Market - Mask Shop Exit",
		"M-SH-P/M": "Market - Potion Shop Exit",
		"ZD-SH/ZD": "Zora's Domain - Shop Exit",
		"KV-BOTW/KV": "Kakariko V. - Bottom of the Well Exit",
		"DMT-DC/DM": "Death M.T. - Dodongo's Cavern Exit",
		"KF-DT/KF": "Kokiri Forest - Deku Tree Exit",
		"DMC-FIT/DMC": "Death M.C. - Fire Temple Exit",
		"SFM-FOT/SFM": "Sacred F.M. - Forest Temple Exit",
		"GF-GTG/GF": "Gerudo Fortress - G.T.G. Exit",
		"ZF-IC/ZF": "Zora's Fountain - Ice Cavern Exit",
		"ZF-JJB/ZF": "Zora's Fountain - Jaba Jaba's Belly Exit",
		"LLR-T/LLR": "Lon Lon Ranch - Tower Exit",
		"GU-SHT/GU": "Graveyard - Shadow Temple Exit",
		"DC-SPT/DC": "Desert Colossus - Spirit Temple Exit",
		"LH-WT/LH": "Lake Hylia - Water Temple Exit",
		"M-TCG/M": "Market - Treasure Chest Game Exit",
		"LLR-TH/LLR": "Lon Lon Ranch - Talon's House Exit",
		"TOTC-TOT/TOTC": "Temple of Time Courtyard - ToT Exit",
		"KV-W/KV": "Kakariko V. - Windmill Exit",
		"CG/CG-GFF-C": "Castle Grounds - Great F.F. Entr. (Child)",
		"CG/M": "Castle Grounds - Market Exit",
		"DC/DC-GFF": "Desert Colossus - Great F.F. Entr.",
		"DC/DC-SPT": "Desert Colossus - Spirit Temple Entr.",
		"DC/HW": "Desert Colossus - Haunted Wasteland",
		"DMT/DMT-DC": "Death M.T. - Dodongo's Cavern Entr.",
		"DMC/DMC-GFF": "Death M.C. - Great F.F. Entr.",
		"DMC/DMC-FIT": "Death M.C. - Fire Temple Entr.",
		"DMC/DMT": "Death Mountain Crater - Summit",
		"DMC/GC": "Death M.C. - Darunia's Chamber",
		"DMT/DMT-GFF": "Death Mountain Trail - Great F.F. Entr.",
		"DMT/DMC": "Death Mountain Trail - Death Mtn Crater",
		"DMT/GC": "Death Mountain Trail - Goron City",
		"DMT/KV": "Death Mountain Trail - Kakariko Gate",
		"GL/GL-DH": "Graveyard - Dampe's Hut Entr.",
		"GU/GU-SHT": "Graveyard - Shadow Temple Entr.",
		"GL/KV": "Graveyard - Kakariko Village",
		"GC/GC-SH": "Goron City - Shop Entr.",
		"GC/DMC": "Goron City - Darunia's Chamber to DMC",
		"GC/DMT": "Goron City - Death Mountain Trail",
		"GC/LW": "Goron City - Warp to Lost Woods",
		"CG/CG-GFF-A": "Castle Grounds - Great F.F. Entr. (Adult)",
		"GF/GF-GTG": "Gerudo Fortress - G.T.G. Entr.",
		"GF/GV": "Gerudo Fortress - Gerudo Valley",
		"GF/HW": "Gerudo Fortress - Haunted Wasteland",
		"GV/GV-CT": "Gerudo Valley - Carpenter's Tent Entr.",
		"GV/GF": "Gerudo Valley - Gerudo Fortress",
		"GV/HF": "Gerudo Valley - Hyrule Field",
		"GV/LH": "Gerudo Valley - Lake Hylia",
		"HF/GV": "Hyrule Field - Gerudo Valley",
		"HF/KV": "Hyrule Field - Kakariko Village",
		"HF/LH": "Hyrule Field - Lake Hylia",
		"HF/LLR": "Hyrule Field - Lon Lon Ranch",
		"HF/LWB": "Hyrule Field - Lost Woods Bridge",
		"HF/ME": "Hyrule Field - Market Entr.",
		"HF/ZR": "Hyrule Field - Zora's River",
		"HW/DC": "Haunted Wasteland - Desert Colossus",
		"HW/GF": "Haunted Wasteland - Gerudo Fortress",
		"KF/KF-HOT": "Kokiri Forest - House of Twins Entr. ",
		"KF/KF-KIAH": "Kokiri Forest - Know-it-all House Entr.",
		"KF/KF-LH": "Kokiri Forest - Link's House Entr.",
		"KF/KF-MH": "Kokiri Forest - Mido's House Entr.",
		"KF/KF-SH": "Kokiri Forest - Shop Entr.",
		"KF/KF-SAH": "Kokiri Forest - Saria's House Entr.",
		"KF/KF-DT": "Kokiri Forest - Deku Tree Entr.",
		"KF/LW": "Kokiri Forest - Lost Woods",
		"KF/LWB": "Kokiri Forest - Lost Woods Bridge",
		"KV/KV-CC": "Kakariko V. - Hole in Impa's House",
		"KV/KV-CH": "Kakariko V. - Carpenter's House Entr.",
		"KV/KV-HOS": "Kakariko V. - House of Skulltula Entr.",
		"KV/KV-IM": "Kakariko V. - Impa's House Entr.",
		"KVB/KVB-ODM": "Kakariko V. - Odd Medicine Bldg Entr.",
		"KV/KV-SG": "Kakariko V. - Shooting Gallery Entr.",
		"KV/KV-SH-B": "Kakariko V. - Bazaar Entr.",
		"KV/BOTW-T": "Kakariko V. - Bottom of the Well Entr.",
		"KV/KV-W": "Kakariko V. - Windmill Entr.",
		"KV/DMT": "Kakariko V. - Death Mountain Trail",
		"KV/GL": "Kakariko V. - Graveyard Entr.",
		"GU/GL": "Graveyard - Warp Pad Fence",
		"KV/HF": "Kakariko V. - Hyrule Field",
		"KV/KVB": "To Kakariko V. Backyard",
		"KV/KV-SH-P": "Kakariko V. - Potion Shop Front Entr.",
		"KVB/KV": "To Kakariko V. Frontyard",
		"KVB/KV-SH-P": "Kakariko V. - Potion Shop Back Entr.",
		"LH/LH-FH": "Lake Hylia - Fishing Hole Entr.",
		"LH/LH-LL": "Lake Hylia - Lakeside Lab Entr.",
		"LH/LH-WT": "Lake Hylia - Water Temple Entr.",
		"LH/HF": "Lake Hylia - Hyrule Field",
		"LH/ZD": "Lake Hylia - Passage to Zora's Domain",
		"LLR/LLR-S": "Lon Lon Ranch - Stables Entr.",
		"LLR/LLR-T": "Lon Lon Ranch - Tower Entr.",
		"LLR/LLR-TH": "Lon Lon Ranch - Talon's House Entr.",
		"LLR/HF": "Lon Lon Ranch - Hyrule Field",
		"LW/GC": "Lost Woods - Warp to Goron City",
		"LW/KF": "Lost Woods - Exit",
		"LW/SFM": "Lost Woods - Sacred Forest Meadow",
		"LW/ZR": "Lost Woods - Warp to Zora's River",
		"LWB/HF": "Lost Woods Bridge - Hyrule Field",
		"LWB/KF": "Lost Woods Bridge - Kokiri Forest",
		"M/M-BB": "Market - Bombchu Bowling Entr.",
		"M/M-MGH": "Market - Man in Green House Entr.",
		"M/M-SG": "Market - Shooting Gallery Entr.",
		"M/M-SH-B": "Market - Bazaar Entr.",
		"M/M-SH-BC": "Market - Bombchu Shop Entr.",
		"M/M-SH-M": "Market - Mask Shop Entr.",
		"M/M-SH-P": "Market - Potion Shop Entr.",
		"M/M-TCG": "Market - Treasure Chest Game Entr.",
		"M/CG": "Market - Castle Grounds",
		"M/ME": "Market - Market Entr.",
		"M/TOTC": "Market - Temple of Time Courtyard",
		"ME/ME-GH": "Market Entr. - Guard House Entr.",
		"ME/HF": "Market Entr. - Hyrule Field",
		"ME/M": "Market Entr. - Market",
		"SFM/SFM-FOT": "Sacred F.M. - Forest Temple Entr.",
		"SFM/LW": "Sacred F.M. - Lost Woods",
		"KV-SH-P/KV": "Kakariko V. - Potion Shop Front Exit",
		"KV-SH-P/KVB": "Kakariko V. - Potion Shop Back Exit",
		"TOTC/TOTC-TOT": "Temple of Time Courtyard - ToT Entr.",
		"TOTC/M": "Temple of Time Courtyard - Market",
		"ZD/ZD-SH": "Zora's Domain - Shop Entr.",
		"ZD/LH": "Zora's Domain - Warp to Lake Hylia",
		"ZD/ZF": "Zora's Domain - Zora's Fountain",
		"ZD/ZR": "Zora's Domain - Zora's River",
		"ZF/ZF-GFF": "Zora's Fountain - Great F.F. Entr.",
		"ZF/ZF-IC": "Zora's Fountain - Ice Cavern Entr.",
		"ZF/ZF-JJB": "Zora's Fountain - Jaba Jaba's Belly Entr.",
		"ZF/ZD": "Zora's Fountain - Zora's Domain",
		"ZR/HF": "Zora's River - Hyrule Field",
		"ZR/LW": "Zora's River - Warp to Lost Woods",
		"ZR/ZD": "Zora's River - Zora's Domain",

		"LH/OWL-LH": "Owl Warp in Lake Hylia",
		"DMT/OWL-DMT": "Owl Warp in Lake Hylia",

	} as Record<string, string>,

	auto_add: [
		["KV/KVB", "KVB/KV"],
		["GV/LH", "LH/GV"],
		["LH/OWL-LH", "OWL-LH/LH"],
		["DMT/OWL-DMT", "OWL-DMT/DMT"],
		["GU/GL", "GL/GU"]
	] as [string, string][],

	adult_only: [
		"SPWN-A",

		// Kakariko Village
		"KV/KV-SG",     // Shooting Gallery
		"KV/KV-SH-B",   // Bazaar
		"KVB/KV-SH-P",  // Back entrance to potion shop
		"KV-SH-P/KVB",  // Back exit  TODO: clip through?

		// Castle Grounds
		"CG/CG-GFF-A",  // GFF

		"GV/GV-CT",    // Carpenter's Tent Entrance
		"GV/GV-G-FS",  // Grotto behind Carpenter's Tent
		"GL/GL-G-D",   // Dampe's grave
	] as string[],

	child_only: [
		"SPWN-C",

		"LH/OWL-LH",
		"DMT/OWL-DMT",

		// Buildings in market
		"M/M-BB",
		"M/M-MGH",
		"M/M-SG",
		"M/M-SH-B",
		"M/M-SH-BC",
		"M/M-SH-M",
		"M/M-SH-P",
		"M/M-TCG",

		// Warp to/from zora's domain
		"ZD/LH",
		"LH/ZD",

		// Entrance to Jaba Jaba's belly
		"ZF/ZF-JJB",

		// Grottos
		"CG/CG-G",    // Castle grounds
		"LLR/LLR-G",  // Lon Lon Ranch
		
		// Castle Grounds
		"CG/CG-GFF-C",  // GFF
	] as string[],

	one_way: [
		"GV/LH",
		"GU/GL",
		"LH/OWL-LH",
		"DMT/OWL-DMT",
	] as string[],

	no_add: [
		"KVB",
		"OWL-LH",
		"OWL-DMT",
	] as string[],

	warps: {
		"OC-POL": "Prelude of Light",
		"OC-MOF": "Minuet of Forest",
		"OC-BOF": "Bolero of Fire",
		"OC-SOW": "Serenade of Water",
		"OC-NOS": "Nocturne of Shadow",
		"OC-ROS": "Requiem of Spirit",
		"SPWN-A": "Adult Spawn",
		"SPWN-C": "Child Spawn",
	} as Record<string, string>,

	owls: {
		"OWL-LH": "Lake Hylia Owl Flight",
		"OWL-DMT": "Death Mountain Trail Owl Flight",
	} as Record<string, string>
};
