export const CFG = {
	areas: {
		"CG": "Castle Grounds",
		"DC-SPT": "Spirit Temple",
		"DC": "Desert Colossus",
		"DMC-FIT": "Death Mountain Crater - Fire Temple",
		"DMC": "Death Mountain Crater",
		"DMT-DC": "Dodongo's Cavern",
		"DMT": "Death Mountain Trail",
		"G-DH": "Dampe's Hut",
		"GU-SHT": "Shadow Temple",
		"GL": "Graveyard - Lower",
		"GU": "Graveyard - Upper",
		"GC-SH": "Goron City Shop",
		"GC": "Goron City",
		"GF-GTG": "Gerudo Training Grounds",
		"GF": "Gerudo Fortress",
		"GV-CT": "Gerudo Valley - Carpenter's Tent",
		"GV": "Gerudo Valley",
		"HF": "Hyrule Field",
		"HW": "Haunted Wasteland",
		"KF-DT": "Deku Tree",
		"KF-HOT": "House of Twins",
		"KF-KIAH": "House of the Know It All Brothers",
		"KF-LH": "Link's House",
		"KF-MH": "Mido's House",
		"KF-SAH": "Saria's House",
		"KF-SH": "Kokiri Forest Shop",
		"KF": "Kokiri Forest",
		"KV-BOTW": "Bottom of the Well",
		"KV-CC": "Hole in Impa's House",
		"KV-CH": "Carpenter's House",
		"KV-HOS": "House of Skulltula",
		"KV-IM": "Impa's House",
		"KV-SG": "Kakariko Village Shooting Gallery",
		"KV-SH-B": "Kakariko Village Bazaar",
		"KV-SH-P": "Kakariko Village Potion Shop",
		"KV-W": "Windmill",
		"KV": "Kakariko Village",
		"KVB": "Kakariko Village Backyard",
		"KVB-ODM": "Kakariko Village Odd Medicine Building",
		"LH-FH": "Fishing Hole",
		"LH-LL": "Lakeside Lab",
		"LH-WT": "Water Temple",
		"LH": "Lake Hylia",
		"LLR-S": "Lon Lon Ranch Stables",
		"LLR-T": "Lon Lon Ranch Tower",
		"LLR-TH": "Talon's House",
		"LLR": "Lon Lon Ranch",
		"LW": "Lost Woods",
		"LWB": "Lost Woods Bridge",
		"M-BB": "Bombchu Bowling",
		"M-MGH": "Market - Man in Green Residence",
		"M-SG": "Market Shooting Gallery",
		"M-SH-B": "Market Bazaar",
		"M-SH-BC": "Market Bombchu Shop",
		"M-SH-M": "Market Mask Shop",
		"M-SH-P": "Market Potion Shop",
		"M-TCG": "Market Treasure Chest Game",
		"M": "Market",
		"ME-GH": "Guard House",
		"ME": "Market Entrance",
		"SFM-FOT": "Forest Temple",
		"SFM": "Sacred Forest Meadow",
		"TOTC-TOT": "Temple of Time",
		"TOTC": "Temple of Time Courtyard",
		"ZD-SH": "Zora's Domain Shop",
		"ZD": "Zora's Domain",
		"ZF-IC": "Ice Cavern",
		"ZF-JJB": "Jaba Jaba's Belly",
		"ZF": "Zora's Fountain",
		"ZR": "Zora's River",


		"CG-G": "Grotto, Breakable Walls",
		"DC-G": "Grotto, Two Scrubs",
		"DMC-G-H": "Grotto, Three Scrubs",
		"DMC-G-U": "Grotto, Chest",
		"DMT-G-C": "Grotto, Cow",
		"DMT-G-S": "Grotto, Chest",
		"G-G-D": "Grotto, Dampe's Grave",
		"G-G-HP": "Grotto, Single ReDead",
		"G-G-RF": "Grotto, Royal Family Tomb",
		"G-G-S": "Grotto, Chest and Fairy Fountain",
		"GC-G": "Grotto, Three Scrubs",
		"GF-G": "Grotto, Fairy Fountain",
		"GV-G-FS": "Grotto, Two Scrubs",
		"GV-G-O": "Grotto, Octorok",
		"HF-G-C": "Grotto, Spider Webs",
		"HF-G-F": "Grotto, Fairy Fountain",
		"HF-G-IF": "Grotto, Single Scrub",
		"HF-G-NK": "Grotto, Gold Skulltula",
		"HF-G-NM": "Grotto, Chest",
		"HF-G-O": "Grotto, Chest",
		"HF-G-SE": "Grotto, Chest",
		"HF-G-T": "Grotto, Pool",
		"KV-G": "Grotto, Two ReDeads",
		"KF-G": "Grotto, Chest",
		"KVB-G": "Grotto, Chest",
		"LH-G": "Grotto, Three Scrubs",
		"LLR-G": "Grotto, Three Scrubs",
		"LW-G-DT": "Grotto, Deku Theater",
		"LW-G-NS": "Grotto, Chest",
		"LW-G-S": "Grotto, Two Scrubs",
		"SFM-G-F": "Grotto, Fairy Fountain",
		"SFM-G-S": "Grotto, Two Scrubs",
		"SFM-G-W": "Grotto, Wolfos",
		"ZD-G": "Grotto, Fairy Fountain",
		"ZR-G-F": "Grotto, Fairy Fountain",
		"ZR-G-O": "Grotto, Chest",
		"ZR-G-S": "Grotto, Two Scrubs",
		"CG-GFF-C": "Great Fairy Fountain (Din's Fire)",
		"DC-GFF": "Great Fairy Fountain (Nayru's Love)",
		"DMC-GFF": "Great Fairy Fountain (Double Magic)",
		"DMT-GFF": "Great Fairy Fountain (Magic Meter)",
		"CG-GFF-A": "Great Fairy Fountain (Double Defense)",
		"ZF-GFF": "Great Fairy Fountain (Farore's Wind)",

		"OWL-LH": "Owl Lake Hylia",
		"OWL-DMT": "Death Mountain Trail Owl",
	} as Record<string, string>,

	doors: {
		"M-BB/M": "Market - Bombchu Bowling Exit",
		"KV-CC/KV": "Kakariko Village - Hole in Impa's House Exit",
		"KV-CH/KV": "Kakariko Village - Carpenter's House Exit",
		"GV-CT/GV": "Gerudo Valley - Carpenter's Tent Exit",
		"GL-DH/GL": "Graveyard - Dampe's Hut Exit",
		"LH-FH/LH": "Lake Hylia - Fishing Hole Exit",
		"CG-G/CG": "Grotto, Breakable Walls",
		"DC-G/DC": "Grotto, Two Scrubs",
		"DMC-G-H/DMC": "Grotto, Three Scrubs",
		"DMC-G-U/DMC": "Grotto, Chest",
		"DMT-G-C/DM": "Grotto, Cow",
		"DMT-G-S/DM": "Grotto, Chest",
		"G-G-D/G": "Grotto, Dampe's Grave",
		"G-G-HP/G": "Grotto, Single ReDead",
		"G-G-RF/G": "Grotto, Royal Family Tomb",
		"G-G-S/G": "Grotto, Chest and Fairy Fountain",
		"GC-G/GC": "Grotto, Three Scrubs",
		"GF-G/GF": "Grotto, Fairy Fountain",
		"GV-G-FS/GV": "Grotto, Two Scrubs",
		"GV-G-O/GV": "Grotto, Octorok",
		"HF-G-C/HF": "Grotto, Spider Webs",
		"HF-G-F/HF": "Grotto, Fairy Fountain",
		"HF-G-IF/HF": "Grotto, Single Scrub",
		"HF-G-NK/HF": "Grotto, Gold Skulltula",
		"HF-G-NM/HF": "Grotto, Chest",
		"HF-G-O/HF": "Grotto, Chest",
		"HF-G-SE/HF": "Grotto, Chest",
		"HF-G-T/HF": "Grotto, Pool",
		"KV-G/KV": "Grotto, Two ReDeads",
		"KF-G/KF": "Grotto, Chest",
		"KVB-G/KVB": "Grotto, Chest",
		"LH-G/LH": "Grotto, Three Scrubs",
		"LLR-G/LLR": "Grotto, Three Scrubs",
		"LW-G-DT/LW": "Grotto, Deku Theater",
		"LW-G-NS/LW": "Grotto, Chest",
		"LW-G-S/LW": "Grotto, Two Scrubs",
		"SFM-G-F/SFM": "Grotto, Fairy Fountain",
		"SFM-G-S/SFM": "Grotto, Two Scrubs",
		"SFM-G-W/SFM": "Grotto, Wolfos",
		"ZD-G/ZD": "Grotto, Fairy Fountain",
		"ZR-G-F/ZR": "Grotto, Fairy Fountain",
		"ZR-G-O/ZR": "Grotto, Chest",
		"ZR-G-S/ZR": "Grotto, Two Scrubs",

		"CG/CG-G": "Castle Grounds Grotto Entrance",
		"DC/DC-G": "Desert Colossus Grotto Entrance",
		"DMC/DMC-G-H": "Death Mountain Crater Grotto Entrance, Boulder",
		"DMC/DMC-G-U": "Death Mountain Crater Grotto Entrance, Upper",
		"DM/DMT-G-C": "Death Mountain Trail Grotto Entrance, Cow",
		"DM/DMT-G-S": "Death Mountain Trail Grotto Entrance, Ring of Rocks",
		"GL/GL-G-D": "Graveyard Grave Entrance, Dampe's Grave",
		"GL/GL-G-HP": "Graveyard Grave Entrance, Back row, 4th from right",
		"GL/GL-G-RF": "Graveyard Grave Entrance, Royal Family Tomb",
		"GL/GL-G-S": "Graveyard Grave Entrance, Front row, 2nd from left",
		"GC/GC-G": "Goron City Grotto Entrance",
		"GF/GF-G": "Gerudo Fortress Grotto Entrance",
		"GV/GV-G-FS": "Gerudo Valley Grotto Entrance, Behind Tent",
		"GV/GV-G-O": "Gerudo Valley Grotto Entrance, Boulder",
		"HF/HF-G-C": "Hyrule Field Grotto Entrance, Near Gerudo Valley",
		"HF/HF-G-F": "Hyrule Field Grotto Entrance, Across Market Moat",
		"HF/HF-G-IF": "Hyrule Field Grotto Entrance, Inside Fence",
		"HF/HF-G-NK": "Hyrule Field Grotto Entrance, Outside Kakariko",
		"HF/HF-G-NM": "Hyrule Field Grotto Entrance, Outside Market",
		"HF/HF-G-O": "Hyrule Field Grotto Entrance, Open",
		"HF/HF-G-SE": "Hyrule Field Grotto Entrance, Southeast",
		"HF/HF-G-T": "Hyrule Field Grotto Entrance, Halfway Between Market and Ranch",
		"KV/KV-G": "Kakariko Village Grotto Entrance, Entrance",
		"KF/KF-G": "Kokiri Forest Grotto Entrance",
		"KVB/KVB-G": "Kakariko Village Grotto Entrance, Backyard",
		"LH/LH-G": "Lake Hylia Grotto Entrance",
		"LLR/LLR-G": "Lon Lon Ranch Grotto Entrance",
		"LW/LW-G-DT": "Lost Woods Grotto Entrance, Beside Tree",
		"LW/LW-G-NS": "Lost Woods Grotto Entrance, Beside Goron City Warp",
		"LW/LW-G-S": "Lost Woods Grotto Entrance, Boulder",
		"SFM/SFM-G-F": "Sacred Forest Meadow Grotto Entrance, At Foot of Ladder",
		"SFM/SFM-G-S": "Sacred Forest Meadow Grotto Entrance, Outside Forest Temple",
		"SFM/SFM-G-W": "Sacred Forest Meadow Grotto Entrance, Entrance",
		"ZD/ZD-G": "Zora's Domain Grotto Entrance",
		"ZR/ZR-G-F": "Zora's River Grotto Entrance, Boulder",
		"ZR/ZR-G-O": "Zora's River Grotto Entrance, Open",
		"ZR/ZR-G-S": "Zora's River Grotto Entrance, Ring of Rocks",

		"CG-GFF-C/CG": "Great Fairy Fountain Exit (Din's Fire)",
		"DC-GFF/DC": "Great Fairy Fountain Exit (Naryru's Love)",
		"DMC-GFF/DMC": "Great Fairy Fountain Exit (Double Magic)",
		"DMT-GFF/DMT": "Great Fairy Fountain Exit (Magic Meter)",
		"CG-GFF-A/CG": "Great Fairy Fountain Exit (Double Defense)",
		"ZF-GFF/ZF": "Great Fairy Fountain Exit (Farore's Wind)",
		"KV-HOS/KV": "Kakariko Village - House of Skulltula Exit",
		"KF-HOT/KF": "Kokiri Forest - House of Twins Exit ",
		"KV-IM/KV": "Kakariko Village - Impa's House Exit",
		"KF-KIAH/KF": "Kokiri Forest - Know it all House Exit",
		"KF-LH/KF": "Kokiri Forest - Link's House Exit",
		"LH-LL/LH": "Lake Hylia - Lakeside Lab Exit",
		"M-MGH/M": "Market - Man in Green House Exit",
		"ME-GH/ME": "Market Entrance - Guard House Exit",
		"KF-MH/KF": "Kokiri Forest - Mido's House Exit",
		"KVB-ODM/KVB": "Kakariko Village - Odd Medicine Building Exit",
		"LLR-S/LLR": "Lon Lon Ranch - Ranch Stables Exit",
		"KV-SG/KV": "Kakariko Village - Shooting Gallery Exit",
		"M-SG/M": "Market - Shooting Gallery Exit",
		"KV-SH-B/KV": "Kakariko Village - Bazaar Exit",
		"M-SH-B/M": "Market - Bazaar Exit",
		"M-SH-BC/M": "Market - Bombchu Shop Exit",
		"GC-SH/GC": "Goron City - Shop Exit",
		"KF-SAH/KF": "Kokiri Forest - Saria's House Exit",
		"KF-SH/KF": "Kokiri Forest - Shop Exit",
		"M-SH-M/M": "Market - Mask Shop Exit",
		"M-SH-P/M": "Market - Potion Shop Exit",
		"ZD-SH/ZD": "Zora's Domain - Shop Exit",
		"KV-BOTW/KV": "Kakariko Village - Bottom of the Well Exit",
		"DMT-DC/DM": "Death Mountain Trail - Dodongo's Cavern Exit",
		"KF-DT/KF": "Kokiri Forest - Deku Tree Exit",
		"DMC-FIT/DMC": "Death Mountain Crater - Fire Temple Exit",
		"SFM-FOT/SFM": "Sacred Forest Meadow - Forest Temple Exit",
		"GF-GTG/GF": "Gerudo Fortress - Gerudo Training Grounds Exit",
		"ZF-IC/ZF": "Zora's Fountain - Ice Cavern Exit",
		"ZF-JJB/ZF": "Zora's Fountain - Jaba Jaba's Belly Exit",
		"LLR-T/LLR": "Lon Lon Ranch - Tower Exit",
		"GU-SHT/GU": "Graveyard - Shadow Temple Exit",
		"DC-SPT/DC": "Desert Colossus - Spirit Temple Exit",
		"LH-WT/LH": "Lake Hylia - Water Temple Exit",
		"M-TCG/M": "Market - Treasure Chest Game Exit",
		"LLR-TH/LLR": "Lon Lon Ranch - Talon's House Exit",
		"TOTC-TOT/TOTC": "Temple of Time Courtyard - Temple of Time Exit",
		"KV-W/KV": "Kakariko Village - Windmill Exit",
		"CG/CG-GFF-C": "Castle Grounds - Great Fairy Fountain Entrance (Child)",
		"CG/M": "Castle Grounds - Market Exit",
		"DC/DC-GFF": "Desert Colossus - Great Fairy Fountain Entrance",
		"DC/DC-SPT": "Desert Colossus - Spirit Temple Entrance",
		"DC/HW": "Desert Colossus - Haunted Wasteland",
		"DMT/DMT-DC": "Death Mountain Trail - Dodongo's Cavern Entrance",
		"DMC/DMC-GFF": "Death Mountain Crater - Great Fairy Fountain Entrance",
		"DMC/DMC-FIT": "Death Mountain Crater - Fire Temple Entrance",
		"DMC/DMT": "Death Mountain Crater - Summit",
		"DMC/GC": "Death Mountain Crater - Darunia's Chamber",
		"DMT/DMT-GFF": "Death Mountain Trail - Great Fairy Fountain Entrance",
		"DMT/DMC": "Death Mountain Trail - Death Mountain Crater",
		"DMT/GC": "Death Mountain Trail - Goron City",
		"DMT/KV": "Death Mountain Trail - Kakariko Gate",
		"GL/GL-DH": "Graveyard - Dampe's Hut Entrance",
		"GU/GU-SHT": "Graveyard - Shadow Temple Entrance",
		"GL/KV": "Graveyard - Kakariko Village",
		"GC/GC-SH": "Goron City - Shop Entrance",
		"GC/DMC": "Goron City - Darunia's Chamber to Death Mountain Crater",
		"GC/DMT": "Goron City - Death Mountain Trail",
		"GC/LW": "Goron City - Warp to Lost Woods",
		"CG/CG-GFF-A": "Castle Grounds - Great Fairy Fountain Entrance (Adult)",
		"GF/GF-GTG": "Gerudo Fortress - Gerudo Training Grounds Entrance",
		"GF/GV": "Gerudo Fortress - Gerudo Valley",
		"GF/HW": "Gerudo Fortress - Haunted Wasteland",
		"GV/GV-CT": "Gerudo Valley - Carpenter's Tent Entrance",
		"GV/GF": "Gerudo Valley - Gerudo Fortress",
		"GV/HF": "Gerudo Valley - Hyrule Field",
		"GV/LH": "Gerudo Valley - Lake Hylia",
		"HF/GV": "Hyrule Field - Gerudo Valley",
		"HF/KV": "Hyrule Field - Kakariko Village",
		"HF/LH": "Hyrule Field - Lake Hylia",
		"HF/LLR": "Hyrule Field - Lon Lon Ranch",
		"HF/LWB": "Hyrule Field - Lost Woods Bridge",
		"HF/ME": "Hyrule Field - Market Entrance",
		"HF/ZR": "Hyrule Field - Zora's River",
		"HW/DC": "Haunted Wasteland - Desert Colossus",
		"HW/GF": "Haunted Wasteland - Gerudo Fortress",
		"KF/KF-HOT": "Kokiri Forest - House of Twins Entrance ",
		"KF/KF-KIAH": "Kokiri Forest - Know-it-all House Entrance",
		"KF/KF-LH": "Kokiri Forest - Link's House Entrance",
		"KF/KF-MH": "Kokiri Forest - Mido's House Entrance",
		"KF/KF-SH": "Kokiri Forest - Kokiri Forest Shop Entrance",
		"KF/KF-SAH": "Kokiri Forest - Saria's House Entrance",
		"KF/KF-DT": "Kokiri Forest - Deku Tree Entrance",
		"KF/LW": "Kokiri Forest - Lost Woods",
		"KF/LWB": "Kokiri Forest - Lost Woods Bridge",
		"KV/KV-CC": "Kakariko Village - Hole in Impa's House",
		"KV/KV-CH": "Kakariko Village - Carpenter's House Entrance",
		"KV/KV-HOS": "Kakariko Village - House of Skulltula Entrance",
		"KV/KV-IM": "Kakariko Village - Impa's House Entrance",
		"KVB/KVB-ODM": "Kakariko Village - Odd Medicine Building Entrance",
		"KV/KV-SG": "Kakariko Village - Shooting Gallery Entrance",
		"KV/KV-SH-B": "Kakariko Village - Bazaar Entrance",
		"KV/BOTW-T": "Kakariko Village - Bottom of the Well Entrance",
		"KV/KV-W": "Kakariko Village - Windmill Entrance",
		"KV/DMT": "Kakariko Village - Death Mountain Trail",
		"KV/GL": "Kakariko Village - Graveyard Entrance",
		"GU/GL": "Graveyard - Jump from Warp Pad",
		"KV/HF": "Kakariko Village - Hyrule Field",
		"KV/KVB": "To Kakariko Village Backyard",
		"KV/KV-SH-P": "Kakariko Village - Potion Shop Front Entrance",
		"KVB/KV": "To Kakariko Village Frontyard",
		"KVB/KV-SH-P": "Kakariko Village - Potion Shop Back Entrance",
		"LH/LH-FH": "Lake Hylia - Fishing Hole Entrance",
		"LH/LH-LL": "Lake Hylia - Lakeside Lab Entrance",
		"LH/LH-WT": "Lake Hylia - Water Temple Entrance",
		"LH/HF": "Lake Hylia - Hyrule Field",
		"LH/ZD": "Lake Hylia - Passage to Zora's Domain",
		"LLR/LLR-S": "Lon Lon Ranch - Stables Entrance",
		"LLR/LLR-T": "Lon Lon Ranch - Tower Entrance",
		"LLR/LLR-TH": "Lon Lon Ranch - Talon's House Entrance",
		"LLR/HF": "Lon Lon Ranch - Hyrule Field",
		"LW/GC": "Lost Woods - Warp to Goron City",
		"LW/KF": "Lost Woods - Exit",
		"LW/SFM": "Lost Woods - Sacred Forest Meadow",
		"LW/ZR": "Lost Woods - Warp to Zora's River",
		"LWB/HF": "Lost Woods Bridge - Hyrule Field",
		"LWB/KF": "Lost Woods Bridge - Kokiri Forest",
		"M/M-BB": "Market - Bombchu Bowling Entrance",
		"M/M-MGH": "Market - Man in Green House Entrance",
		"M/M-SG": "Market - Shooting Gallery Entrance",
		"M/M-SH-B": "Market - Bazaar Entrance",
		"M/M-SH-BC": "Market - Bombchu Shop Entrance",
		"M/M-SH-M": "Market - Mask Shop Entrance",
		"M/M-SH-P": "Market - Potion Shop Entrance",
		"M/M-TCG": "Market - Treasure Chest Game Entrance",
		"M/CG": "Market - Castle Grounds",
		"M/ME": "Market - Market Entrance",
		"M/TOTC": "Market - Temple of Time Courtyard",
		"ME/ME-GH": "Market Entrance - Guard House Entrance",
		"ME/HF": "Market Entrance - Hyrule Field",
		"ME/M": "Market Entrance - Market",
		"SFM/SFM-FOT": "Sacred Forest Meadow - Forest Temple Entrance",
		"SFM/LW": "Sacred Forest Meadow - Lost Woods",
		"KV-SH-P/KV": "Kakariko Village - Potion Shop Front Exit",
		"KV-SH-P/KVB": "Kakariko Village - Potion Shop Back Exit",
		"TOTC/TOTC-TOT": "Temple of Time Courtyard - Temple of Time Entrance",
		"TOTC/M": "Temple of Time Courtyard - Market",
		"ZD/ZD-SH": "Zora's Domain - Shop Entrance",
		"ZD/LH": "Zora's Domain - Warp to Lake Hylia",
		"ZD/ZF": "Zora's Domain - Zora's Fountain",
		"ZD/ZR": "Zora's Domain - Zora's River",
		"ZF/ZF-GFF": "Zora's Fountain - Great Fairy Fountain Entrance",
		"ZF/ZF-IC": "Zora's Fountain - Ice Cavern Entrance",
		"ZF/ZF-JJB": "Zora's Fountain - Jaba Jaba's Belly Entrance",
		"ZF/ZD": "Zora's Fountain - Zora's Domain",
		"ZR/HF": "Zora's River - Hyrule Field",
		"ZR/LW": "Zora's River - Warp to Lost Woods",
		"ZR/ZD": "Zora's River - Zora's Domain",

		"LH/OWL-LH": "Owl Warp in Lake Hylia",
		"DMT/OWL-DMT": "Owl Warp in Lake Hylia",

	} as Record<string, string>,

	auto_add: [
		["KV/KVB", "KVB/KV"],
		["GV/LH", "LH/GV"],
		["LH/OWL-LH", "OWL-LH/LH"],
		["DMT/OWL-DMT", "OWL-DMT/DMT"],
	] as [string, string][],

	adult_only: [
		"SPWN-A",

		// Kakariko Village
		"KV/KV-SG",     // Shooting Gallery
		"KV/KV-SH-B",   // Bazaar
		"KVB/KV-SH-P",  // Back entrance to potion shop
		"KV-SH-P/KVB",  // Back exit  TODO: clip through?

		// Castle Grounds
		"CG/CG-GFF-A",  // GFF

		"GV/GV-CT",    // Carpenter's Tent Entrance
		"GV/GV-G-FS",  // Grotto behind Carpenter's Tent
		"GL/GL-G-D",   // Dampe's grave
	] as string[],

	child_only: [
		"SPWN-C",

		"LH/OWL-LH",
		"DMT/OWL-DMT",

		// Buildings in market
		"M/M-BB",
		"M/M-MGH",
		"M/M-SG",
		"M/M-SH-B",
		"M/M-SH-BC",
		"M/M-SH-M",
		"M/M-SH-P",
		"M/M-TCG",

		// Warp to/from zora's domain
		"ZD/LH",
		"LH/ZD",

		// Entrance to Jaba Jaba's belly
		"ZF/ZF-JJB",

		// Grottos
		"CG/CG-G",    // Castle grounds
		"LLR/LLR-G",  // Lon Lon Ranch
		
		// Castle Grounds
		"CG/CG-GFF-C",  // GFF
	] as string[],

	one_way: [
		"GV/LH",
		"GU/GL",
		"LH/OWL-LH",
		"DMT/OWL-DMT",
	] as string[],

	no_add: [
		"KVB",
		"OWL-LH",
		"OWL-DMT",
	] as string[],

	warps: {
		"OC-POL": "Prelude of Light",
		"OC-MOF": "Minuet of Forest",
		"OC-BOF": "Bolero of Fire",
		"OC-SOW": "Serenade of Water",
		"OC-NOS": "Nocturne of Shadow",
		"OC-ROS": "Requiem of Spirit",
		"SPWN-A": "Adult Spawn",
		"SPWN-C": "Child Spawn",
	} as Record<string, string>,

	owls: {
		"OWL-LH": "Lake Hylia Owl Flight",
		"OWL-DMT": "Death Mountain Trail Owl Flight",
	} as Record<string, string>
};
